"""empty message

Revision ID: 534f444d749b
Revises: 5843827a7cf2
Create Date: 2019-06-05 19:35:28.618688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '534f444d749b'
down_revision = '5843827a7cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_settings', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('base_settings', sa.Column('contact', sa.String(length=255), nullable=True))
    op.add_column('base_settings', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('base_settings', sa.Column('programming_langs', sa.String(length=255), nullable=True))
    op.add_column('base_settings', sa.Column('projects', sa.String(length=255), nullable=True))
    op.add_column('base_settings', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_base_settings_username'), 'base_settings', ['username'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_base_settings_username'), table_name='base_settings')
    op.drop_column('base_settings', 'username')
    op.drop_column('base_settings', 'projects')
    op.drop_column('base_settings', 'programming_langs')
    op.drop_column('base_settings', 'country')
    op.drop_column('base_settings', 'contact')
    op.drop_column('base_settings', 'city')
    # ### end Alembic commands ###
