"""empty message

Revision ID: 9c27d95fac3f
Revises: 39f3b61ea117
Create Date: 2019-06-11 21:58:20.257066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c27d95fac3f'
down_revision = '39f3b61ea117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmed', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed')
    # ### end Alembic commands ###
